# **Numpy**
NumPy is a Python library used for working with arrays

NumPy stands for Numerical Python and it is an open source project.


Why is Numpy Faster? - Fixed Type

* Faster to read less bytes of memory.
* No type cheacked when iterating through objects.

In [1]:
# import numpy
import numpy as np

In [ ]:
# to check the version of numpy
import numpy as np
print(np.__version__)

1.25.2


In [2]:
# creating an array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
print("a[0]",a[0])
print("a[1]",a[1])
print("a[2]",a[2])
print("a[3]",a[3])

a[0] 1
a[1] 2
a[2] 3
a[3] 4


In [ ]:
# creating an asarray
a = [1,2,3,4]
b = np.asarray(a,dtype=int)
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
# creating 2-dimensional
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)


In [ ]:
 # Get Dimension
 a.ndim

2

In [ ]:
# Get shape
a.shape

(2, 4)

In [ ]:
a.dtype

dtype('int64')

In [9]:
# Get the shape/size of numpy array
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("a shape :",a.shape)
print("a size : ", a.size)
print("a ndim : ", a.ndim)
print("------------------")
print("b shape : ",b.shape)
print("b. size :" , b.size)
print("b ndim :",b.ndim)

a shape : (5,)
a size :  5
a ndim :  1
------------------
b shape :  (2, 5)
b. size : 10
b ndim : 2


In [11]:
# adding the 2 arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.add(a,b)
print(c)

d = a + b
print(d)


[ 6  8 10 12]
[ 6  8 10 12]


In [12]:
# the dot product of the two numpy arrays
a = np.array([1,2])
b = np.array([3,2])
c = np.dot(a,b)
print(c)

# this the process while we use dot
# c = [(a[0]*b[0]) + (a[1]*b[1])]

7


# **Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [ ]:
# To Cheack the datatype use dtype
a = np.array([1,2,3,4])
print(a.dtype)

int64


In [ ]:
a = np.array(["swamy","ranga","reddy"])
print(a.dtype)

<U5


In [ ]:
# Converting the data type
a = np.array([1,2,3,4],dtype="S")
print(a.dtype)

|S1


# **Slicing**
Like lists, we can slice the numpy array.Slicing in python means taking the elements from the given index to another given index

we pass slice like this : [start:end]. the element at end index is not being included in the output.

In [ ]:
import numpy as np
a = np.array([10,20,30,40,50])
b = a[1:4]
b

array([20, 30, 40])

In [ ]:
# Set the fourth element and fifth element to 300 and 400
a[3:5] = 400,500
a

array([ 10,  20,  30, 400, 500])

In [ ]:
# We can also define the steps in slicing, like this: [start:end:step].
a = np.array([10,20,30,40,50])
b = a[0:5:2]
b

array([10, 30, 50])

In [ ]:
# numpy array addition
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])
c = np.add(a,b)
c

array([11, 22, 33, 44, 55])

In [ ]:
# Numpy Array Multiplication
d = np.multiply(a,b)
d

array([ 10,  40,  90, 160, 250])

In [ ]:
#  we cn divide teo arrays and assign it to m
m = np.divide(a,b)
m

array([10., 10., 10., 10., 10.])

In [ ]:
# The dot product of the two numpy arrays a and b is given by:
np.dot(a,b)
# dot works
# (a[0]* b[0] + a[1]*b[1] +a[2]*b[2])

550

In [ ]:
# adding 5 to evey value
a =np.array([10,20,30,40,50])
a + 5


array([15, 25, 35, 45, 55])

In [ ]:
# creating a 2-D array
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
print("array : ",b)
print("------------")
print("dimension : ",b.ndim)
print("--------------")
print("shape : ",b.shape)

array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
dimension :  2
--------------
shape :  (3, 3)


In [ ]:
# Access the element on the first row and first and second columns
b[0][0:2]

array([1, 2])

In [ ]:
# Access the element on the first and second rows and third column
b[0:2,2]

array([3, 6])

In [ ]:
# Multiply b with 2
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
import requests
url="https://in.nothing.tech/"
r=requests.get(url)
r

<Response [200]>

In [16]:
# We can view the status code using the attribute status_code.
r.status_code

200

In [18]:
# You can view the request headers:
z = r.request.headers
for i in z:
  print(i)

User-Agent
Accept-Encoding
Accept
Connection


In [23]:
head =r.headers


In [24]:
head["date"]

'Wed, 31 Jul 2024 11:39:45 GMT'

In [25]:
head["Content-Type"]

'text/html; charset=utf-8'

In [26]:
r.encoding

'utf-8'

In [27]:
r.text[0:100]

'<!doctype html>\n<html class="html " lang="en" >\n  <head>\n    <meta charset="utf-8">\n    <meta http-e'